CREATE DATABASE IF NOT EXISTS dezc_dwh;

DROP VIEW IF EXISTS dezc_dwh.raw;

CREATE OR REPLACE VIEW dezc_dwh.raw
AS
SELECT json
FROM file(
    'import/raw/repositories/extract_date=*/owner=*/repo=*/*.json',
    'RawBLOB',
    'json String'
);


CREATE OR REPLACE VIEW dezc_dwh.raw_normalized
AS
SELECT
    JSONExtractString(meta_raw, 'entity') AS meta_entity,
    JSONExtractString(meta_raw, 'owner') AS meta_owner,
    JSONExtractString(meta_raw, 'repo') AS meta_repo,
    JSONExtractString(meta_raw, 'full_name') AS meta_full_name,
    JSONExtractString(meta_raw, 'run_date') AS meta_run_date,
    parseDateTime64BestEffortOrNull(JSONExtractString(meta_raw, 'fetched_at')) AS meta_fetched_at,
    JSONExtractUInt(data_raw, 'id') AS id,
    JSONExtractString(data_raw, 'node_id') AS node_id,
    JSONExtractString(data_raw, 'name') AS name,
    JSONExtractString(data_raw, 'full_name') AS full_name,
    JSONExtractBool(data_raw, 'private') AS private,
    JSONExtractRaw(data_raw, 'owner') AS owner_json,
    JSONExtractString(data_raw, 'html_url') AS html_url,
    JSONExtractString(data_raw, 'description') AS description,
    JSONExtractBool(data_raw, 'fork') AS fork,
    JSONExtractString(data_raw, 'url') AS url,
    JSONExtractString(data_raw, 'forks_url') AS forks_url,
    JSONExtractString(data_raw, 'keys_url') AS keys_url,
    JSONExtractString(data_raw, 'collaborators_url') AS collaborators_url,
    JSONExtractString(data_raw, 'teams_url') AS teams_url,
    JSONExtractString(data_raw, 'hooks_url') AS hooks_url,
    JSONExtractString(data_raw, 'issue_events_url') AS issue_events_url,
    JSONExtractString(data_raw, 'events_url') AS events_url,
    JSONExtractString(data_raw, 'assignees_url') AS assignees_url,
    JSONExtractString(data_raw, 'branches_url') AS branches_url,
    JSONExtractString(data_raw, 'tags_url') AS tags_url,
    JSONExtractString(data_raw, 'blobs_url') AS blobs_url,
    JSONExtractString(data_raw, 'git_tags_url') AS git_tags_url,
    JSONExtractString(data_raw, 'git_refs_url') AS git_refs_url,
    JSONExtractString(data_raw, 'trees_url') AS trees_url,
    JSONExtractString(data_raw, 'statuses_url') AS statuses_url,
    JSONExtractString(data_raw, 'languages_url') AS languages_url,
    JSONExtractString(data_raw, 'stargazers_url') AS stargazers_url,
    JSONExtractString(data_raw, 'contributors_url') AS contributors_url,
    JSONExtractString(data_raw, 'subscribers_url') AS subscribers_url,
    JSONExtractString(data_raw, 'subscription_url') AS subscription_url,
    JSONExtractString(data_raw, 'commits_url') AS commits_url,
    JSONExtractString(data_raw, 'git_commits_url') AS git_commits_url,
    JSONExtractString(data_raw, 'comments_url') AS comments_url,
    JSONExtractString(data_raw, 'issue_comment_url') AS issue_comment_url,
    JSONExtractString(data_raw, 'contents_url') AS contents_url,
    JSONExtractString(data_raw, 'compare_url') AS compare_url,
    JSONExtractString(data_raw, 'merges_url') AS merges_url,
    JSONExtractString(data_raw, 'archive_url') AS archive_url,
    JSONExtractString(data_raw, 'downloads_url') AS downloads_url,
    JSONExtractString(data_raw, 'issues_url') AS issues_url,
    JSONExtractString(data_raw, 'pulls_url') AS pulls_url,
    JSONExtractString(data_raw, 'milestones_url') AS milestones_url,
    JSONExtractString(data_raw, 'notifications_url') AS notifications_url,
    JSONExtractString(data_raw, 'labels_url') AS labels_url,
    JSONExtractString(data_raw, 'releases_url') AS releases_url,
    JSONExtractString(data_raw, 'deployments_url') AS deployments_url,
    parseDateTime64BestEffortOrNull(JSONExtractString(data_raw, 'created_at')) AS created_at,
    parseDateTime64BestEffortOrNull(JSONExtractString(data_raw, 'updated_at')) AS updated_at,
    parseDateTime64BestEffortOrNull(JSONExtractString(data_raw, 'pushed_at')) AS pushed_at,
    JSONExtractString(data_raw, 'git_url') AS git_url,
    JSONExtractString(data_raw, 'ssh_url') AS ssh_url,
    JSONExtractString(data_raw, 'clone_url') AS clone_url,
    JSONExtractString(data_raw, 'svn_url') AS svn_url,
    JSONExtractString(data_raw, 'homepage') AS homepage,
    JSONExtractUInt(data_raw, 'size') AS size,
    JSONExtractUInt(data_raw, 'stargazers_count') AS stargazers_count,
    JSONExtractUInt(data_raw, 'watchers_count') AS watchers_count,
    JSONExtractString(data_raw, 'language') AS language,
    JSONExtractBool(data_raw, 'has_issues') AS has_issues,
    JSONExtractBool(data_raw, 'has_projects') AS has_projects,
    JSONExtractBool(data_raw, 'has_downloads') AS has_downloads,
    JSONExtractBool(data_raw, 'has_wiki') AS has_wiki,
    JSONExtractBool(data_raw, 'has_pages') AS has_pages,
    JSONExtractBool(data_raw, 'has_discussions') AS has_discussions,
    JSONExtractUInt(data_raw, 'forks_count') AS forks_count,
    if(JSONExtractRaw(data_raw, 'mirror_url') = 'null', NULL, JSONExtractString(data_raw, 'mirror_url')) AS mirror_url,
    JSONExtractBool(data_raw, 'archived') AS archived,
    JSONExtractBool(data_raw, 'disabled') AS disabled,
    JSONExtractUInt(data_raw, 'open_issues_count') AS open_issues_count,
    JSONExtractRaw(data_raw, 'license') AS license_json,
    JSONExtractBool(data_raw, 'allow_forking') AS allow_forking,
    JSONExtractBool(data_raw, 'is_template') AS is_template,
    JSONExtractBool(data_raw, 'web_commit_signoff_required') AS web_commit_signoff_required,
    JSONExtractBool(data_raw, 'has_pull_requests') AS has_pull_requests,
    JSONExtractString(data_raw, 'pull_request_creation_policy') AS pull_request_creation_policy,
    arrayMap(x -> JSONExtractString(x), JSONExtractArrayRaw(data_raw, 'topics')) AS topics,
    JSONExtractString(data_raw, 'visibility') AS visibility,
    JSONExtractUInt(data_raw, 'forks') AS forks,
    JSONExtractUInt(data_raw, 'open_issues') AS open_issues,
    JSONExtractUInt(data_raw, 'watchers') AS watchers,
    JSONExtractString(data_raw, 'default_branch') AS default_branch,
    if(JSONExtractRaw(data_raw, 'temp_clone_token') = 'null', NULL, JSONExtractString(data_raw, 'temp_clone_token')) AS temp_clone_token,
    JSONExtractRaw(data_raw, 'custom_properties') AS custom_properties_json,
    JSONExtractRaw(data_raw, 'organization') AS organization_json,
    JSONExtractUInt(data_raw, 'network_count') AS network_count,
    JSONExtractUInt(data_raw, 'subscribers_count') AS subscribers_count,
    JSONExtractString(owner_raw, 'login') AS owner_login,
    JSONExtractUInt(owner_raw, 'id') AS owner_id,
    JSONExtractString(owner_raw, 'node_id') AS owner_node_id,
    JSONExtractString(owner_raw, 'avatar_url') AS owner_avatar_url,
    JSONExtractString(owner_raw, 'gravatar_id') AS owner_gravatar_id,
    JSONExtractString(owner_raw, 'url') AS owner_url,
    JSONExtractString(owner_raw, 'html_url') AS owner_html_url,
    JSONExtractString(owner_raw, 'followers_url') AS owner_followers_url,
    JSONExtractString(owner_raw, 'following_url') AS owner_following_url,
    JSONExtractString(owner_raw, 'gists_url') AS owner_gists_url,
    JSONExtractString(owner_raw, 'starred_url') AS owner_starred_url,
    JSONExtractString(owner_raw, 'subscriptions_url') AS owner_subscriptions_url,
    JSONExtractString(owner_raw, 'organizations_url') AS owner_organizations_url,
    JSONExtractString(owner_raw, 'repos_url') AS owner_repos_url,
    JSONExtractString(owner_raw, 'events_url') AS owner_events_url,
    JSONExtractString(owner_raw, 'received_events_url') AS owner_received_events_url,
    JSONExtractString(owner_raw, 'type') AS owner_type,
    JSONExtractString(owner_raw, 'user_view_type') AS owner_user_view_type,
    JSONExtractBool(owner_raw, 'site_admin') AS owner_site_admin,
    JSONExtractString(license_raw, 'key') AS license_key,
    JSONExtractString(license_raw, 'name') AS license_name,
    JSONExtractString(license_raw, 'spdx_id') AS license_spdx_id,
    if(JSONExtractRaw(license_raw, 'url') = 'null', NULL, JSONExtractString(license_raw, 'url')) AS license_url,
    JSONExtractString(license_raw, 'node_id') AS license_node_id,
    JSONExtractString(organization_raw, 'login') AS organization_login,
    JSONExtractUInt(organization_raw, 'id') AS organization_id,
    JSONExtractString(organization_raw, 'node_id') AS organization_node_id,
    JSONExtractString(organization_raw, 'avatar_url') AS organization_avatar_url,
    JSONExtractString(organization_raw, 'gravatar_id') AS organization_gravatar_id,
    JSONExtractString(organization_raw, 'url') AS organization_url,
    JSONExtractString(organization_raw, 'html_url') AS organization_html_url,
    JSONExtractString(organization_raw, 'followers_url') AS organization_followers_url,
    JSONExtractString(organization_raw, 'following_url') AS organization_following_url,
    JSONExtractString(organization_raw, 'gists_url') AS organization_gists_url,
    JSONExtractString(organization_raw, 'starred_url') AS organization_starred_url,
    JSONExtractString(organization_raw, 'subscriptions_url') AS organization_subscriptions_url,
    JSONExtractString(organization_raw, 'organizations_url') AS organization_organizations_url,
    JSONExtractString(organization_raw, 'repos_url') AS organization_repos_url,
    JSONExtractString(organization_raw, 'events_url') AS organization_events_url,
    JSONExtractString(organization_raw, 'received_events_url') AS organization_received_events_url,
    JSONExtractString(organization_raw, 'type') AS organization_type,
    JSONExtractString(organization_raw, 'user_view_type') AS organization_user_view_type,
    JSONExtractBool(organization_raw, 'site_admin') AS organization_site_admin
FROM
(
    SELECT
        json,
        JSONExtractRaw(json, '_meta') AS meta_raw,
        JSONExtractRaw(json, 'data') AS data_raw,
        JSONExtractRaw(JSONExtractRaw(json, 'data'), 'owner') AS owner_raw,
        JSONExtractRaw(JSONExtractRaw(json, 'data'), 'license') AS license_raw,
        JSONExtractRaw(JSONExtractRaw(json, 'data'), 'organization') AS organization_raw
    FROM dezc_dwh.raw
) s;
